#!/bin/sh

PATH_SCRIPT=$(dirname $0)

## Select the llfile
if [ ! -f "$1" ]
then
    echo "Provide an original llxml-file"
    exit 1
else 
    LLXML=$1
fi

## Get the requested language
if [ -z "$2" ]
then
    echo "Provide the language you wish to extract to xlf."
    exit 2
else
    TARGET_LANG_OUT=$2
fi

if [ ! -z "$3" ]
then
    TARGET_LANG_IN=$3
else
    TARGET_LANG_IN=$TARGET_LANG_OUT
fi

## Wash the target name
if [ "$2" = "default" ]
then
    OUTFILE=$(echo $LLXML | sed -e 's/\.xml$/.xlf/')
else
    OUTFILE=$(echo $TARGET_LANG_OUT.$LLXML | sed -e 's/\.xml$/.xlf/')
fi

## Get the product name / that is the extension key
__get_extdir() {
    while [ "$PWD" != "/" ] && [ ! -f ext_emconf.php ]
    do
	cd ..
    done

    if [ "$PWD" = "/" ]
    then
	echo "error"
	return
    fi

    pwd | tr '/' "\n" | tail -n1
}
PRODUCT=$(__get_extdir)
if [ "$PRODUCT" = "error" ]
then
    echo "Error: Failing to get product name"
    exit 4
fi


## Get a proper date for the Xlf-file
XLFDATE=$(date +%Y-%m-%dT%H:%M:%SZ)


## Process
if [ -f "$OUTFILE" ]
then
    echo "$OUTFILE already exist"
    exit 3
else
    xsltproc \
	--stringparam target_lang_out $TARGET_LANG_OUT \
	--stringparam product $PRODUCT \
	--stringparam target_lang_in $TARGET_LANG_IN \
	--stringparam xlfdate $XLFDATE \
	$PATH_SCRIPT/llxml2xliff.xsl $LLXML | \
	sed -e 's/^[ \t\v\f]*//g' -e 's/[ \t\v\f]*$//g' -e '/^$/d' | \
	tr "\240\302" '  ' | \
	xmllint --noent --encode UTF-8 --format - > $OUTFILE
fi
